# Generated by Django 3.2.20 on 2024-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('model', 'version')},
        ),
    ]
